agent: our
bs: 24
epochs: 199
exp_id: rvt2
num_workers: 3
peract:
  add_rgc_loss: true
  amp: true
  bnb: true
  lambda_weight_l2: 0.0001
  lr: 1.0e-07
  lr_cos_dec: false
  num_rotation_classes: 72
  optimizer_type: lamb
  transform_augmentation: true
  transform_augmentation_rpy:
  - 0.0
  - 0.0
  - 45.0
  transform_augmentation_xyz:
  - 0.125
  - 0.125
  - 0.125
  warmup_steps: 0
peract_official:
  cfg_path: configs/peract_official_config.yaml
resume: runs/rvt2/model_99.pth
rvt:
  gt_hm_sigma: 1.5
  img_aug: 0.0
  move_pc_in_bound: true
  place_with_mean: false
sample_distribution_mode: task_uniform
tasks: all
train_iter: 160000

